exp_name:
seed: 1
torch_deterministic: True
cuda: True
track: False
capture_video: False
env_id: vssStrat-v0
num_envs: 10
total_timesteps: 5e7

wandb:
  project_name: 'cleanRL'
  entity:

defaults:
  - agent: DylamDDPG
  - _self_
